# Generated by Django 5.1.5 on 2025-01-28 18:33

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('G', 'Gestion de Polizas'), ('T', 'Tramitacion de Siniestro'), ('T', 'Tareas Administrativas')], default='G', max_length=1, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la aseguradora')),
                ('nro_poliza', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de polizas')),
            ],
        ),
        migrations.CreateModel(
            name='CartaAval',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de presupuesto')),
                ('fecha_siniestro', models.DateField(verbose_name='Fecha de siniestro')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('diagnostico', models.CharField(max_length=255, verbose_name='Diagnostico')),
                ('procedimiento', models.CharField(max_length=255, verbose_name='Procedimiento')),
                ('clinica', models.CharField(max_length=255, verbose_name='Clinica')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('paciente', models.CharField(max_length=255, verbose_name='Paciente')),
                ('informe_resultado', models.ImageField(upload_to='photos/cartaval/')),
                ('informe_ampliado', models.ImageField(upload_to='photos/cartaval/')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.aseguradora')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de factura')),
                ('diagnostico', models.CharField(max_length=255, verbose_name='Diagnostico')),
                ('fecha_siniestro', models.DateField(verbose_name='fecha de siniestro')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de factura')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('paciente', models.CharField(max_length=255, verbose_name='Paciente')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('informe_ampliado', models.ImageField(upload_to='photos/reembolso/')),
                ('informe_resultado', models.ImageField(upload_to='photos/reembolso/')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.aseguradora')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCartaAval',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de siniestro')),
                ('estatus', models.CharField(choices=[('P', 'Por revisar'), ('R', 'Revisado')], default='P', max_length=1, verbose_name='Estatus')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.administrador')),
                ('carta_aval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.cartaaval')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReembolso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de siniestro')),
                ('estatus', models.CharField(choices=[('P', 'Por revisar'), ('R', 'Revisado')], default='P', max_length=1, verbose_name='Estatus')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.administrador')),
                ('reembolso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.reembolso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('telefono_opcional', models.IntegerField(blank=True, null=True, verbose_name='Telefono opcional')),
                ('correo', models.CharField(max_length=255, verbose_name='correo electronico')),
                ('vigencia_desde', models.DateField(verbose_name='Vigencia desde')),
                ('vigencia_hasta', models.DateField(verbose_name='vigencia hasta')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.aseguradora')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reembolso',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parientes', models.CharField(choices=[('P', 'Padre'), ('M', 'Madre'), ('H', 'Hijo'), ('H', 'Hija'), ('H', 'Hermano'), ('H', 'Hermana')], default='P', max_length=1, verbose_name='Familiar')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.titular')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartaaval',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
