# Generated by Django 5.1.5 on 2025-02-11 16:55

import Apps.Aplicacion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[Apps.Aplicacion.models.validate_only_letters])),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, validators=[Apps.Aplicacion.models.validate_only_letters])),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='La cédula debe tener al menos 8 dígitos.'), django.core.validators.MaxValueValidator(999999999, message='La cédula debe tener como máximo 9 dígitos.')])),
                ('nombre', models.CharField(max_length=100, validators=[Apps.Aplicacion.models.validate_only_letters])),
                ('apellido', models.CharField(max_length=100, validators=[Apps.Aplicacion.models.validate_only_letters])),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personal',
            },
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='aseguradora',
        ),
        migrations.RemoveField(
            model_name='cartaaval',
            name='aseguradora',
        ),
        migrations.RemoveField(
            model_name='titular',
            name='aseguradora',
        ),
        migrations.RemoveField(
            model_name='cartaaval',
            name='username',
        ),
        migrations.RemoveField(
            model_name='solicitudcartaaval',
            name='carta_aval',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='titular',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='username',
        ),
        migrations.RemoveField(
            model_name='solicitudreembolso',
            name='reembolso',
        ),
        migrations.RemoveField(
            model_name='solicitudcartaaval',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='solicitudreembolso',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='titular',
            name='username',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.etiqueta')),
                ('presentado_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.direccion')),
                ('presentado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.personal')),
                ('resuelto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Aplicacion.ticket')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.DeleteModel(
            name='Aseguradora',
        ),
        migrations.DeleteModel(
            name='CartaAval',
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
        migrations.DeleteModel(
            name='Reembolso',
        ),
        migrations.DeleteModel(
            name='SolicitudCartaAval',
        ),
        migrations.DeleteModel(
            name='SolicitudReembolso',
        ),
        migrations.DeleteModel(
            name='Titular',
        ),
    ]
