# Generated by Django 5.1.5 on 2025-02-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_direccion_etiqueta_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
