# Generated by Django 5.1.5 on 2025-02-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_alter_ticket_resuelto_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resuelto_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
