# Generated by Django 5.1.5 on 2025-02-18 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_alter_ticket_resuelto_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='rol',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
