# Generated by Django 5.1.5 on 2025-02-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_remove_administrador_rol_alter_ticket_resuelto_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.etiqueta'),
        ),
    ]
