# Generated by Django 5.1.5 on 2025-02-21 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_alter_ticket_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_resueltos', to=settings.AUTH_USER_MODEL),
        ),
    ]
