# Generated by Django 5.1.5 on 2025-02-21 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_ticket_asignado_a_alter_ticket_resuelto_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
