# Generated by Django 5.1.5 on 2025-02-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_alter_ticket_asignado_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
    ]
