# Generated by Django 5.1.5 on 2025-02-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
    ]
