# Generated by Django 5.1.5 on 2025-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0011_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='ticket',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='Aplicacion.etiqueta'),
        ),
    ]
