# Generated by Django 5.1.5 on 2025-02-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0012_remove_ticket_etiqueta_ticket_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='ticket',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.etiqueta'),
        ),
    ]
