# Generated by Django 5.1.5 on 2025-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0013_remove_ticket_etiquetas_ticket_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='ticket',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, null=True, to='Aplicacion.etiqueta'),
        ),
    ]
