# Generated by Django 5.1.5 on 2025-02-28 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0014_remove_ticket_etiqueta_ticket_etiqueta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='username',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='etiqueta',
            field=models.ManyToManyField(blank=True, to='Aplicacion.etiqueta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cédula'),
        ),
    ]
