# Generated by Django 5.1.5 on 2025-03-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0011_remove_usuario_cedula_alter_usuario_username'),
        ('Aplicacion', '0014_remove_ticket_etiqueta_ticket_etiqueta'),
    ]

    operations = [
    ]
