# Generated by Django 5.1.5 on 2025-03-14 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0016_alter_personal_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='La cédula debe tener al menos 7 dígitos.'), django.core.validators.MaxValueValidator(99999999, message='La cédula debe tener como máximo 8 dígitos.')]),
        ),
    ]
